name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Rust MUSL Compile
      uses: rhysnewell/rust-cargo-musl-action@v0.1.20
      id: 'compile'
      with:
        command: 'build'
        flags: '--features vendored-openssl'
    - uses: actions/upload-artifact@v2
      with:
        name: binary
        path: ${{ steps.compile.outputs.release-dir }}/binary
